### ISSUE TITLE
Missing installation information in README

### ISSUE THREAD

**Issue by smurthys** [16bit-ykiko/vscode-compiler-explorer#26]
Frankly, I have been wondering for years why a VS (Code/Studio) extension like this has not existed. So, thank you for your initiative.

I'm eager to try this extension. Installation is probably just a matter of downloading the files in the repo and pointing VS Code to the directory containing the files, but it will be helpful if the README has a brief section on how to do all that.

Again, thank you for the extension.

**Comment by 16bit-ykiko** [comment]
Hi, you can find the plugin in VSCode Marketplace. Here is the [address](https://marketplace.visualstudio.com/items?itemName=ykiko.vscode-compiler-explorer).

**Comment by smurthys** [comment]
Thank you, and I found the extension on the marketplace.

BTW I created PR #27 with an Installation section in README. Please feel free to accept or reject.
