### ISSUE TITLE
Back-End | Wrap Compiler Explorer API

### ISSUE THREAD

**Issue by 16bit-ykiko** [16bit-ykiko/vscode-compiler-explorer#5]
Compiler Explorer provides some [API](https://github.com/compiler-explorer/compiler-explorer/blob/main/docs/API.md), wrap it for easy usage.

**Comment by T1t4m1un** [comment]
https://github.com/T1t4m1un/compiler-explorer-for-vscode/blob/main/src/utils/api.ts

**Comment by 16bit-ykiko** [comment]
Some filter options are not supported in specific compiler, get the detailed information from the API and disable to change the corresponding checkboxes.

This has been finished by https://github.com/16bit-ykiko/vscode-compiler-explorer/commit/4dd1b7e11fdf6a5b714f5b4d58e9c82a9384ec3b.
